openapi: 3.0.1
info:
  title: Pakjai API Documentation
  description: API documentation for the Pakjai Burnout Checker App
  version: "1.0"
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/assessments:
    get:
      tags:
      - assessment-controller
      operationId: findAll
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Assessment"
    post:
      tags:
      - assessment-controller
      operationId: save
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AssessmentRequest"
        required: true
      responses:
        "200":
          description: OK
  /api/health:
    get:
      tags:
      - health-check-controller
      operationId: health
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
  /api/assessments/{id}:
    get:
      tags:
      - assessment-controller
      operationId: findById
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Assessment"
    delete:
      tags:
      - assessment-controller
      operationId: delete
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
          format: uuid
      responses:
        "200":
          description: OK
components:
  schemas:
    AssessmentAnswerRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        assessmentId:
          type: string
          format: uuid
        seq:
          type: integer
          format: int32
        answer:
          type: string
        point:
          type: integer
          format: int32
    AssessmentRequest:
      type: object
      properties:
        id:
          type: string
          format: uuid
        seq:
          type: integer
          format: int32
        question:
          type: string
        type:
          type: string
        status:
          type: string
        answers:
          type: array
          items:
            $ref: "#/components/schemas/AssessmentAnswerRequest"
    Assessment:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        updatedAt:
          type: string
          format: date-time
        updatedBy:
          type: string
        version:
          type: integer
          format: int32
        id:
          type: string
          format: uuid
        seq:
          type: integer
          format: int32
        question:
          type: string
        type:
          type: string
        status:
          type: string
        answers:
          type: array
          items:
            $ref: "#/components/schemas/AssessmentAnswer"
    AssessmentAnswer:
      type: object
      properties:
        createdAt:
          type: string
          format: date-time
        createdBy:
          type: string
        updatedAt:
          type: string
          format: date-time
        updatedBy:
          type: string
        version:
          type: integer
          format: int32
        id:
          type: string
          format: uuid
        assessment:
          $ref: "#/components/schemas/Assessment"
        seq:
          type: integer
          format: int32
        answer:
          type: string
        point:
          type: integer
          format: int32
