server:
  port: 8080

spring:
  application:
    name: pakjai-burnout-checker
  jackson:
    serialization:
      indent-output: true
  datasource:
    url: jdbc:postgresql://172.16.0.70:5432/postgres
    username: postgres
    password: P@ssw0rd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    root: INFO
    org:
      springframework:
        web: ERROR